name: docker-build-push
#https://github.com/marketplace/actions/build-and-push-docker-images

on:
  push:
    branches: [eva-practice]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["base"]
        docker-file: ["Dockerfile"]
        module-name: ["r", "eva-practice"]
    steps:
      - uses: actions/checkout@v2
      - name: Set version and tags
        id: ver
        run: |
          VERSION=`cat tools/${{matrix.module-name}}/VERSION`
          echo "version: $VERSION"
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: streitlab/custom-nf-modules-${{matrix.module-name}}
          path: tools/${{matrix.module-name}}
          dockerfile: tools/${{matrix.module-name}}/${{matrix.docker-file}}
          tags: latest,${{matrix.tag}}-${{steps.ver.outputs.version}}
